# Generated by Django 2.1 on 2018-08-21 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='start date'),
        ),
    ]
