# Generated by Django 2.1 on 2018-08-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180821_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_year',
            field=models.IntegerField(default=2018, verbose_name='End Year'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_year',
            field=models.IntegerField(default=2018, verbose_name='Start Year'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('AD', 'anno Domini'), ('BC', 'before Christ')], default='AD', max_length=2, verbose_name='Status'),
        ),
    ]
