# Generated by Django 2.1 on 2018-08-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180824_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_month',
            field=models.IntegerField(default='00', verbose_name='End Month'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_month',
            field=models.IntegerField(default='00', verbose_name='Start Month'),
        ),
    ]
