# Generated by Django 2.1 on 2018-08-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180824_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_day',
            field=models.IntegerField(default=30, verbose_name='Start Day'),
        ),
        migrations.AlterField(
            model_name='event',
            name='julian_end',
            field=models.CharField(choices=[('AD', 'anno Domini'), ('BC', 'before Christ')], default='AD', max_length=2, verbose_name='Julian End'),
        ),
        migrations.AlterField(
            model_name='event',
            name='julian_start',
            field=models.CharField(choices=[('AD', 'anno Domini'), ('BC', 'before Christ')], default='AD', max_length=2, verbose_name='Julian Start'),
        ),
    ]
